/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



volatile uint8_t EXTI0_Flag = 0;
 uint32_t EXTI1_Flag = 0;
volatile uint8_t EXTI2_Flag = 0;


void SysTick_AppCall(void){
	EXTI0_Flag++;
}

int main(void)
{

	RCC_enuOscilatorInit(&OSC);
	RCC_enuClocksInit(&CLK);

	STK_enuInit(&STK_strConfigs);

	RCC_enuSetClockState(RCC_GPIOA, true);
	RCC_enuSetClockState(RCC_GPIOB, true);
	RCC_enuSetClockState(RCC_GPIOC, true);

	GPIO_enuSetPinMode(GPIO_PB4, GPIO_General);
	GPIO_enuSetPinType(GPIO_PB4, GPIO_OUT_PushPull);
	GPIO_enuSetPinPull(GPIO_PB4, GPIO_PullUp);
	GPIO_enuSetPinSpeed(GPIO_PB4, GPIO_HighSpeed);
	while(1){

		GPIO_enuSetPinValue(GPIO_PB4,GPIO_Set);
		STK_enuDelay_Blocking(10000);
		GPIO_enuSetPinValue(GPIO_PB4,GPIO_Reset);
		STK_enuDelay_Blocking(10000);

	}

}

